language: c

before_install:
- sudo apt-get update -q
- sudo apt-get install -qq apt-transport-https python-docutils
- curl -L https://packagecloud.io/varnishcache/varnish40/gpgkey | sudo apt-key add -
- echo "deb https://packagecloud.io/varnishcache/varnish40/precise/ precise main" | sudo tee /etc/apt/sources.list.d/varnish-cache.list
- sudo apt-get -q update
- sudo apt-get install varnish libvarnishapi-dev

before_script:
- ./autogen.sh
- ./configure --prefix=/usr
- make -j4

script:
- make check -j4

compiler:
- clang
- gcc
